### ISSUE TITLE
Option for output-file name

### ISSUE THREAD

**Issue by rmueck** [iamleot/transferwee#10]
Great tool!  It would be nice to have an option to specify a name for the output-file. Example:

`transferwee -o /tmp/output-file download https://wetransfer.com/downloads/123lkjfd`

Cheers

**Comment by iamleot** [comment]
Hello rmueck, 

rmueck writes:
> Great tool!  It would be nice to have an option to specify a name for the output-file. Example:
>
> `transferwee -o /tmp/output-file download https://wetransfer.com/downloads/123lkjfd`
> [...]

Thanks!

Would you like to give a look to it and share a possible patch?

(download() needs an extra optional argument to provide a possible
output filename and the argument parsing for the download subparser needs
to be instructed about `-o' option.)

**Comment by rmueck** [comment]
> Thanks! Would you like to give a look to it and share a possible patch? (download() needs an extra optional argument to provide a possible output filename and the argument parsing for the download subparser needs to be instructed about `-o' option.)

Sorry man, i was asking for an enhancement. Sorry i cannot supply a patch

**Comment by iamleot** [comment]
OK, don't worry.  I will implement it!

**Comment by iamleot** [comment]
I have just added support for it via commit 6bcbd3b.

Please note that `-o` is a `download` option (it should be after `download`) so the command incantation should be:

````
transferwee download -o /tmp/output-file https://wetransfer.com/downloads/123lkjfd
````

If you notice any possible issue please let me know!
