### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by sicaboy** [iamleot/transferwee#11]
Traceback (most recent call last):
  File "transferwee.py", line 393, in <module>
    download(u, args.o)
  File "transferwee.py", line 136, in download
    file = _file_unquote(urllib.parse.urlparse(dl_url).path.split('/')[-1])
TypeError: 'str' does not support the buffer interface

**Comment by sicaboy** [comment]
Do you have a requirements.txt file?

**Comment by iamleot** [comment]
Hello sicaboy,

sicaboy writes:
> [...]
> Traceback (most recent call last):
>   File "transferwee.py", line 393, in <module>
>     download(u, args.o)
>   File "transferwee.py", line 136, in download
>     file = _file_unquote(urllib.parse.urlparse(dl_url).path.split('/')[-1])
> TypeError: 'str' does not support the buffer interface
> [...]

Which Python version is used?

Can you please share a possible URL and the command invocation in order
to reproduce it?

**Comment by iamleot** [comment]
sicaboy writes:
> Do you have a requirements.txt file?

No, there isn't any `requirements.txt' file, only `requests' package is
needed.

(Writing a setup.py and eventually publishing it on pypi is on my TODO
list.)

**Comment by sicaboy** [comment]
> Hello sicaboy, sicaboy writes:
> [...] Traceback (most recent call last): File "transferwee.py", line 393, in <module> download(u, args.o) File "transferwee.py", line 136, in download file = _file_unquote(urllib.parse.urlparse(dl_url).path.split('/')[-1]) TypeError: 'str' does not support the buffer interface [...]
> Which Python version is used? Can you please share a possible URL and the command invocation in order to reproduce it?

Python 3.4.3

https://tonictheagency.wetransfer.com/downloads/b1007789a996ed5ca1f4cbcce49dcda020200514061705/33f3cf17a33ffd18c65815742a76198e20200514061706/ca95fd

**Comment by iamleot** [comment]
sicaboy writes:
> [...]
> https://tonictheagency.wetransfer.com/downloads/b1007789a996ed5ca1f4cbcce49dcda020200514061705/33f3cf17a33ffd18c65815742a76198e20200514061706/ca95fd
> [...]

Thanks!  I can reproduce it and transferwee needs to be instructed about
possible subdomain transfers.

**Comment by iamleot** [comment]
This should be fixed via 31bbb249dd4f7170ff91e6b5eac27e14dfa80f25.

Can you please test it and let me know if you can successfully download
the entire file?


Thanks!

**Comment by sicaboy** [comment]
Thanks, it has another error now 

```
Traceback (most recent call last):
  File "transferwee.py", line 393, in <module>
    download(u, args.o)
  File "transferwee.py", line 134, in download
    dl_url = download_url(url)
  File "transferwee.py", line 111, in download_url
    headers=request_data['headers'])
  File "/usr/lib/python3/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by iamleot** [comment]
I guess that's probably due a too old `requests` version. What version is installed? (`python3 -c 'import requests; print(requests.__version__)'` will probably reveals it)

**Comment by iamleot** [comment]
JFTR, according <https://requests.readdthedocs.io/en/latest/community/updates/#id52> it seems that was added in requests version 2.4.2.

**Comment by sicaboy** [comment]
Yea, you are right.

I was using requests 2.2 and I did `pip3 install requests --upgrade`, Now it's 2.23.

It's working now. Thanks for your help! Leonardo

**Comment by iamleot** [comment]
Yay!

No problem and thank you again for reporting this issue and quick
feedbacks!

**Comment by sicaboy** [comment]
Got a favour to ask. 
Can you hide the URL cause it's a bit confidential though the URL is exposed to the public?

**Comment by iamleot** [comment]
Sure! I have removed all of them in the comments (and removed history edits) and further redacted the URL you have shared.
