### ISSUE TITLE
JSON missing parameter

### ISSUE THREAD

**Issue by fletcher97** [iamleot/transferwee#12]
The script stopped working today. I've been using every day for a while and today the script decided it would not work anymore. I tried a few thing and found out that the method that generates the downloadable url (download_url(url) at line 64) is probably the culprit. this would be a good time to say I'm using this to download only, not upload. At the end of this method the JSON object (j) on has this: {'message': 'Missing parameter :intent'}. Hope you can fix this soon. If you need more info feel free to contact me

**Comment by iamleot** [comment]
Hello fletcher97, 

fletcher97 writes:
> The script stopped working today. I've been using every day for a while and today the script decided it would not work anymore. I tried a few thing and found out that the method that generates the downloadable url (download_url(url) at line 64) is probably the culprit. this would be a good time to say I'm using this to download only, not upload. At the end of this method the JSON object (j) on has this: {'message': 'Missing parameter :intent'}. Hope you can fix this soon. If you need more info feel free to contact me

Thanks for the notice!

Commit 71488b382ba8f10e9d77549bb2f90ce6140d80d2 should fix this issue.

Can you please try it again and let me know if it fixes it for you too?


Thanks!

**Comment by fletcher97** [comment]
I can confirm it worked for me. I tried looking around for a fix to help but you where faster xD. Thanks for the quick fix.

**Comment by iamleot** [comment]
Great!  Thank you for checking it and thanks again for reporting this problem!
