### ISSUE TITLE
All functionality breaks without additional headers

### ISSUE THREAD

**Issue by mrwnwttk** [iamleot/transferwee#14]
Hey! About two hours ago wetransfer started reporting incorrect X-CSRF Tokens despite them correct. This can be fixed by supplying additional headers.

```
def get_headers(session):
    return {
        'x-csrf-token': session.headers['x-csrf-token'],
        'x-requested-with': 'XMLHttpRequest',
    }
```

This can simply be supplied with each post request, here for example in `_prepare_link_upload`:
```
r = session.post(WETRANSFER_UPLOAD_LINK_URL, json=j, headers=get_headers(session))
```

If you'd like me to submit a pull request for this fix just let me know.

**Comment by mrwnwttk** [comment]
Small update: This still isn't quite enough. The transfers expire immediately for some reason.

**Comment by iamleot** [comment]
Whoops, thanks a lot @mrwnwttk!  I will hopefully try to give it a look deeper this UTC-ish evening! (no PRs needed, this is already precious help/information and we can continue discussing about it here!)

**Comment by iamleot** [comment]
@mrwnwttk I have tested both the link upload and email upload and now the problem you have reported should be fixed.  Your debugging and initial solution were also correct AFAICT only `x-requested-with:` header was needed but I have just adjusted `_prepare_session()` to do that.

Can you please check if that fixes the issue for you too?

Thanks!

**Comment by mrwnwttk** [comment]
Can confirm that it's working again! Thanks for the fast response!
