### ISSUE TITLE
Required python version is hardcoded at 3.7

### ISSUE THREAD

**Issue by marcelpaulo** [iamleot/transferwee#3]
The required python version is hardcoded at 3.7:

```
#!/usr/bin/env python3.7
```

so that when I try to run `transferwee`, I get:

```
paulo:~/src/transferwee (master)$ ./transferwee.py --help
/usr/bin/env: ‘python3.7’: No such file or directory
```

I'm running Xubuntu 18.0.02 LTS and the installed python 3 version is:

```
paulo:~/src/transferwee (master)$ python3 --version
Python 3.6.7
```

Shouldn't the `env` shebang require only python3? Like this:

```
#!/usr/bin/env python3
```

I'm not a Python programmer but I had a look around other python 3 programs I have installed, like `quodlibet`, and they all have a shebang like that.

**Comment by iamleot** [comment]
Hello Paulo,

Paulo Marcel Coelho Aragão writes:
> The required python version is hardcoded at 3.7:
> 
> ```
> #!/usr/bin/env python3.7
> ```
> 
> so that when I try to run `transferwee`, I get:
> 
> ```
> paulo:~/src/transferwee (master)$ ./transferwee.py --help
> /usr/bin/env: ‘python3.7’: No such file or directory
> ```
> 
> I'm running Xubuntu 18.0.02 LTS and the installed python 3 version is:
> 
> ```
> paulo:~/src/transferwee (master)$ python3 --version
> Python 3.6.7
> ```
> 
> Shouldn't the `env` shebang require only python3? Like this:
> 
> ```
> #!/usr/bin/env python3
> ```
> 
> I'm not a Python programmer but I had a look around other python 3 programs I have installed, like `quodlibet`, and they all have a shebang like that.
> 

That depends on distribution/package system used: for example in
pkgsrc there isn't any python3 if pkg_alternatives is not used.

At least in pkgsrc there is a `REPLACE_PYTHON' that automatically
transform such shebangs directly to the location of the corresponding
Python interpreter (e.g. `/usr/pkg/bin/python3.7' for Python 3.7).

I think that `transferwee' works with 3.6.x and newer (but probably not
older Python-s as-is!).

Please let me know if adjusting the shebang to just `python3' does
the trick and I will commit it!


Thank you!

**Comment by marcelpaulo** [comment]
> Please let me know if adjusting the shebang to just `python3' does the trick and I will commit it!

Yes, it does the trick!

**Comment by iamleot** [comment]
Hello Paulo,

Paulo Marcel Coelho Aragão writes:
>
> Yes, it does the trick! 
>

Thank you, I have adjusted it!

**Comment by marcelpaulo** [comment]
Perfect, thank you so much, @iamleot!
