### ISSUE TITLE
"IsADirectoryError" error

### ISSUE THREAD

**Issue by emresaracoglu** [iamleot/transferwee#36]
Hello

Thank you for your work.
I encounter this error when I add the path I want the files to download.
For example;

```
web2@serve: transferwee -o /var/downloadedFiles/transferwee/ -v https://wetransfer.com/abcdef
Traceback (most recent call last):
  File "we.py", line 438, in <module>
    download(u, args.o)
  File "we.py", line 155, in download
    with open(file, 'wb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/var/downloadedFiles/transferwee/'
```

Why I am getting this error `IsADirectoryError`?

**Comment by iamleot** [comment]
Hello!
Mmm, probably wrong copypasto? E.g. with latest `transferwee` HEAD this should fails with:

```
$ transferwee -o /tmp/foo -v https://wetransfer.com/abcdef
usage: transferwee [-h] {download,upload} ...
transferwee: error: argument action: invalid choice: '/tmp/foo' (choose from 'download', 'upload')
```

...assuming that it's a `download` command... `-o` expect a path, i.e. it's the output file where it will write, not a directory. Hence why it fails.

I think that calling, e.g.:

```
transferwee download -o /var/downloadedFiles/transferwee/abcd -v https://wetransfer.com/abcdef
```

Will avoid that.

**Comment by emresaracoglu** [comment]
Ciao! 

I think I can't give a directory for the file to download. I need to export a command line with directory and new filename. Thus, instead of the original name of the downloaded file, it saves to the name I gave on the command line.

Like this _and working_;

`python3 we.py download -o /var/downloadedFiles/transferwee/newFileName.zip -v https://wetransfer.com/abcdef`

Is it possible to record with the original name?

**Comment by iamleot** [comment]
Nope. There is a possible TODOs regarding adding a `-d` option to `download/upload` commands to set a base directory.

Possible workaround is to:

```
cd /var/downloadedFiles/transferwee
```

...and run `transferwee` from there.

**Comment by emresaracoglu** [comment]
I see, **thank you** for your time and work.

**Comment by iamleot** [comment]
Closing, already known possible TODO.
