### ISSUE TITLE
Set the exit code to a value > 0 when an error occurs

### ISSUE THREAD

**Issue by marcelpaulo** [iamleot/transferwee#5]
It would be useful if `transferwee` set the exit code to something other than 0 when an error occurs. As of now, it seems that the exit code is always set to 0, even when an error occurs. For instance, trying to upload a non-existent file:

```
paulo:~/tmp$ ls foo
ls: cannot access 'foo': No such file or directory
paulo:~/tmp$ transferwee upload foo
None
paulo:~/tmp$ echo $?
0
```

Of course, I could also capture stdout and check if it's a valid URL: if it isn't, it means there was an error. Checking the exit code feels more natural.

**Comment by iamleot** [comment]
Hello @marcelpaulo!
Whoops, nice catch!  I have just adjusted the two `return None' to more gracefully raise exceptions and then exiting with a non-0 exit status.

Please let me know if that's okay and feel free to close this issue if so!


Thanks again!

**Comment by marcelpaulo** [comment]
Hey, that's really good, @iamleot! Thanks a lot for the swift fix!
