### ISSUE TITLE
upload: file size cannot exceed 15 MB

### ISSUE THREAD

**Issue by jeremyp3** [iamleot/transferwee#70]
as soon as the file size exceeds 15 MB, I get this error: 

$ ./transferwee.py upload /tmp/toto.mp3 -v
Checking that all files exists
Checking for no duplicate filenames
Preparing to upload
Could not find any csrf-token
From storm_upload_token WETRANSFER_STORM_PREFLIGHT URL is: https://storm-eu-west-1.wetransfer.net/api/v2/batch/preflight
From storm_upload_token WETRANSFER_STORM_BLOCK URL is: https://storm-eu-west-1.wetransfer.net/api/v2/blocks
From storm_upload_token WETRANSFER_STORM_BLOCK URL is: https://storm-eu-west-1.wetransfer.net/api/v2/batch
Get transfer id 6f0651d79de2f01c4c14ed0d93eb185120231022124836
Doing preflight storm
Preparing storm block upload
Traceback (most recent call last):
  File "/tmp/transferwee/./transferwee.py", line 683, in <module>
    print(upload(args.files, args.n, args.m, args.f, args.t))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/transferwee/./transferwee.py", line 587, in upload
    for f, b in zip(files, blocks["data"]["blocks"]):
                           ~~~~~~^^^^^^^^
KeyError: 'data'

use master version  and python3.11 

thanks !

**Comment by iamleot** [comment]
Likely a duplicate of #64 but maybe now the limits of a block is changed.

Thanks for reporting!

**Comment by jeremyp3** [comment]
indeed, it's the same thing.

**Comment by iamleot** [comment]
Re-close as not planned (it was not completed but it is a duplicate, I've added all such info on #64 too and added cross-references to this issue so nothing gets lost).

Thank you again!
