### ISSUE TITLE
Downloading Files - [403] Error on post request

### ISSUE THREAD

**Issue by morph3us-net** [iamleot/transferwee#8]
When trying to download a file I get following error message:
`file = urllib.parse.urlparse(dl_url).path.split('/')[-1]
TypeError: a bytes-like object is required, not 'str'`

I tried to print out "r" from the "download_url" class
(r = requests.post(WETRANSFER_DOWNLOAD_URL.format(transfer_id=transfer_id), json=j),
but only got <Response [403]>.

I believe this is because I am not sending an authorization key with the request, right?
(https://developers.wetransfer.com/documentation#send-request)

**Comment by iamleot** [comment]
Hello morph3us-net, 

morph3us-net writes:
> When trying to download a file I get following error message:
> `file = urllib.parse.urlparse(dl_url).path.split('/')[-1]
> TypeError: a bytes-like object is required, not 'str'`
>
> I tried to print out "r" from the "download_url" class
> (r = requests.post(WETRANSFER_DOWNLOAD_URL.format(transfer_id=transfer_id), json=j),
> but only got <Response [403]>.
>
> I believe this is because I am not sending an authorization key with the request, right?
> (https://developers.wetransfer.com/documentation#send-request)

Nope, that shouldn't needed, transferwee just mimic the behaviour done
when uploading/downloading via web browser and no keys should be
needed.

If you can easily reproduce this issue can you please upload a simple
test file (like a text file with just a couple of characters), share
the download URL and the complete backtrace of the error?


Thanks!


PS: You'll get a 403 error also if you are using transferwee before
    commit ed22bf688bc013dac5b4903ab43951727c54bccb (any version after
    that commit should be okay).  In that case the 403 error was due
    the missing `X-CSRF-Token:' header not sent (seems that it was
    required by wetransfer.com requests in the last 2 weeks).

**Comment by morph3us-net** [comment]
Thank you very much for replying! I am very grateful that you take your time to respond to me!
Please be aware that I am not a professional programmer.

I am purely interested in the download part of the module. I want to integrate the code into a PyQt interface and show the download progress in a bar, hence I am not using the module as is, but want to copy some of the code.
GitHub kinda shreds the code when formatting, so you can see a better version here: https://paste.ofcode.org/ZUnv32fxQDLuFVemaPbtEL
(I stripped the file of all unneeded classes, the argument parsing in the main() and the class comments for better overview)

from typing import List
import os.path
import urllib.parse
import zlib
import requests

WETRANSFER_API_URL = 'https://wetransfer.com/api/v4/transfers'
WETRANSFER_DOWNLOAD_URL = WETRANSFER_API_URL + '/{transfer_id}/download'
WETRANSFER_DEFAULT_CHUNK_SIZE = 5242880

def download_url(url: str) -> str:
    # Follow the redirect if we have a short URL
    if url.startswith('https://we.tl/'):
        r = requests.head(url, allow_redirects=True)
        url = r.url

    recipient_id = None
    params = url.replace('https://wetransfer.com/downloads/', '').split('/')
    print(params)

    if len(params) == 2:
        transfer_id, security_hash = params
    elif len(params) == 3:
        transfer_id, recipient_id, security_hash = params
    else:
        return None

    j = {
        "security_hash": security_hash,
    }
    if recipient_id:
        j["recipient_id"] = recipient_id
    # r = requests.post("https://wetransfer.com/api/v4/transfers/0867ab5bd6323b0857477db024f9df8e20190928225139/download/", json=j)
    r = requests.post(WETRANSFER_DOWNLOAD_URL.format(transfer_id=transfer_id),
                      json=j)

    j = r.json()
    print(r)
    return j.get('direct_link')


def download(url: str) -> None:
    dl_url = download_url(url)
    file = urllib.parse.urlparse(dl_url).path.split('/')[-1]

    r = requests.get(dl_url, stream=True)
    with open(file, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024):
            f.write(chunk)


def main():
    download("https://wetransfer.com/downloads/0867ab5bd6323b0857477db024f9df8e20190928225139/22617d5812cb77ebc59f08891416d0f220190928225139/16b28d")


if __name__ == '__main__':
    main()

This is the full error code I get:

> <Response [403]>
Traceback (most recent call last):
  File "transferwee_shortened001.py", line 57, in <module>
    main()
  File "transferwee_shortened001.py", line 53, in main
    download("https://wetransfer.com/downloads/0867ab5bd6323b0857477db024f9df8e20190928225139/22617d5812cb77ebc59f08891416d0f220190928225139/16b28d")
  File "transferwee_shortened001.py", line 44, in download
    file = urllib.parse.urlparse(dl_url).path.split('/')[-1]
TypeError: a bytes-like object is required, not 'str'

As you can see, the print() on line 38 gives back a 403 response, which in turn throws an error when being parsed, because its "only" a string. On line 33, commented out, you can see I even tried to manually format the download url, just in case, but that didn't help either.

I am pretty sure I broke something then. Could you be so kind and help me out? :)

**Comment by iamleot** [comment]
morph3us-net writes:
> Thank you very much for replying! I am very grateful that you take your time to respond to me!
> Please be aware that I am not a professional programmer.
>

No problem!

> I am purely interested in the download part of the module. I want to integrate the code into a PyQt interface and show the download progress in a bar, hence I am not using the module as is, but want to copy some of the code.
> GitHub kinda shreds the code when formatting, so you can see a better version here: https://paste.ofcode.org/ZUnv32fxQDLuFVemaPbtEL
> (I stripped the file of all unneeded classes, the argument parsing in the main() and the class comments for better overview)
>
> from typing import List
> import os.path
> import urllib.parse
> import zlib
> import requests
>
> WETRANSFER_API_URL = 'https://wetransfer.com/api/v4/transfers'
> WETRANSFER_DOWNLOAD_URL = WETRANSFER_API_URL + '/{transfer_id}/download'
> WETRANSFER_DEFAULT_CHUNK_SIZE = 5242880
>
> def download_url(url: str) -> str:
>     # Follow the redirect if we have a short URL
>     if url.startswith('https://we.tl/'):
>         r = requests.head(url, allow_redirects=True)
>         url = r.url
>
>     recipient_id = None
>     params = url.replace('https://wetransfer.com/downloads/', '').split('/')
>     print(params)
>
>     if len(params) == 2:
>         transfer_id, security_hash = params
>     elif len(params) == 3:
>         transfer_id, recipient_id, security_hash = params
>     else:
>         return None
>
>     j = {
>         "security_hash": security_hash,
>     }
>     if recipient_id:
>         j["recipient_id"] = recipient_id
>     # r = requests.post("https://wetransfer.com/api/v4/transfers/0867ab5bd6323b0857477db024f9df8e20190928225139/download/", json=j)
>     r = requests.post(WETRANSFER_DOWNLOAD_URL.format(transfer_id=transfer_id),
>                       json=j)
>
>     j = r.json()
>     print(r)
>     return j.get('direct_link')
>
>
> def download(url: str) -> None:
>     dl_url = download_url(url)
>     file = urllib.parse.urlparse(dl_url).path.split('/')[-1]
>
>     r = requests.get(dl_url, stream=True)
>     with open(file, 'wb') as f:
>         for chunk in r.iter_content(chunk_size=1024):
>             f.write(chunk)
>
>
> def main():
>     download("https://wetransfer.com/downloads/0867ab5bd6323b0857477db024f9df8e20190928225139/22617d5812cb77ebc59f08891416d0f220190928225139/16b28d")
>
>
> if __name__ == '__main__':
>     main()
>
> This is the full error code I get:
>
> > <Response [403]>
> Traceback (most recent call last):
>   File "transferwee_shortened001.py", line 57, in <module>
>     main()
>   File "transferwee_shortened001.py", line 53, in main
>     download("https://wetransfer.com/downloads/0867ab5bd6323b0857477db024f9df8e20190928225139/22617d5812cb77ebc59f08891416d0f220190928225139/16b28d")
>   File "transferwee_shortened001.py", line 44, in download
>     file = urllib.parse.urlparse(dl_url).path.split('/')[-1]
> TypeError: a bytes-like object is required, not 'str'
>
> As you can see, the print() on line 38 gives back a 403 response, which in turn throws an error when being parsed, because its "only" a string. On line 33, commented out, you can see I even tried to manually format the download url, just in case, but that didn't help either.
>
> I am pretty sure I broke something then. Could you be so kind and help me out? :)
>

JFTR, directly downloading
<https://wetransfer.com/downloads/0867ab5bd6323b0857477db024f9df8e20190928225139/22617d5812cb77ebc59f08891416d0f220190928225139/16b28d>
via `transferwee download ...' works (there is a pugs.zip archive
that seems containing a couple of photographs of dogs :)).

`X-CSRF-Token:' header and associated cookies are not passed and that's
probably why the 403 error is returned.

To address that requests.post() in download_url() needs to have
corresponding `cookies' and `headers' associated as done by current
HEAD (basically they can be populated via `_prepare_request_data()',
that will return a dict with `cookies' and `headers' keys that can be
passed as-is to requests.post() via `cookies' and `headers'
arguments).

**Comment by morph3us-net** [comment]
Okay, I thought I had downloaded a fresh copy after your last commit, but it seems I havent. I integrated the "cookies" and "header" and I am able to download.
As such, I am closing this "issue" (which wasn't even one), I however hope to get your help once more:

I had hoped to get the file size before downloading the file, so I can show the download progress in a progressbar. I thought I could get that with `r.headers["Content-Length"]`, but there is no "Content-Length" key present in the returned request. Is there another way to get that information?

**Comment by iamleot** [comment]
Hello morph3us-net, 

morph3us-net writes:
> Okay, I thought I had downloaded a fresh copy after your last commit, but it seems I havent. I integrated the "cookies" and "header" and I am able to download.
> As such, I am closing this "issue" (which wasn't even one), I however hope to get your help once more:
>
> I had hoped to get the file size before downloading the file, so I can show the download progress in a progressbar. I thought I could get that with `r.headers["Content-Length"]`, but there is no "Content-Length" key present in the returned request. Is there another way to get that information?

Sorry, I don't follow, which request or `r'?

At least always with the link you've shared in this issue
(<https://wetransfer.com/downloads/0867ab5bd6323b0857477db024f9df8e20190928225139/22617d5812cb77ebc59f08891416d0f220190928225139/16b28d>),
it seems there is an r.headers['Content-Length'], in download(), after
line 125:

    r = requests.get(dl_url, stream=True)

you can add:

    size = int(r.headers['Content-Length'])

(in that case size is `204265').

That corresponds to the file downloaded, e.g.:

 % wc -c pugs.zip                                                                                                                   /tmp
   204265 pugs.zip

**Comment by morph3us-net** [comment]
Brilliant! Thank you so much! I tried to get the size from the request in the download_url() function, which is obviously wrong... Everything works now, I really can't thank you enough! Thanks for taking your time to clarify everything up for me!
