### ISSUE TITLE
filename may contain non-ascii characters

### ISSUE THREAD

**Issue by openessays** [iamleot/transferwee#9]
Hello **Leonardo**,
thanks for this good project. I'm using it a lot. My native language is Chinese, when using subcommand 'download', filename is not decoded as Chinese when uploaded filename contains Chinese characters. Could you decode filename before saving it? After line #123, it's better to add "file = urllib.parse.unquote(file)". 

thanks again for this good project!

**Comment by iamleot** [comment]
Hello @openessays ,
I will try to give it a look and unquote the filename!

(However, I think it's a bit more complicated than just `unquote(...)` becouse if `/` or `..` are encoded the file will "escape" the current working directory.)

**Comment by iamleot** [comment]
@openessays, can you please try again? Commit ddeb05d should address that.

Please let me know!  If you notice any problems please share possible problematic URLs as well so I can test that too.

Thanks!

**Comment by openessays** [comment]
Hello **Leonardo**,
I'm sorry to reply so late. I was busy in the past week. I tested your solution by "https://we.tl/t-2KgpsmpEux". it shows it's ok.

thanks for your fixing!
